spring:
  application:
  name: integration-test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
  jpa:
    ddl-auto: create-drop
    show-sql: true

customer:
  api:
    url: http://localhost:666/api/customers